### ISSUE TITLE
firefox,Edge浏览器横向滚动条无法拖动滚动条

### ISSUE THREAD

**Issue by brightlight2017** [JdesHZ/el-table-bar#1]
按照示例使用，表格出现横向滚动条时，在firefox,Edge浏览器下无法拖动横向滚动条，Chrome浏览器下没有问题。

**Comment by JdesEva** [comment]
感谢指出bug，已经复现问题。正在进行修复

**Comment by JdesEva** [comment]
> 按照示例使用，表格出现横向滚动条时，在firefox,Edge浏览器下无法拖动横向滚动条，Chrome浏览器下没有问题。

问题已经修复，稍后即将更新版本，进行代码推送。更新完毕会再次通知，万分感谢对于该插件的支持！

**Comment by JdesEva** [comment]
> 按照示例使用，表格出现横向滚动条时，在firefox,Edge浏览器下无法拖动横向滚动条，Chrome浏览器下没有问题。

已经更新版本，由于OTP验证问题，npm包迁移至 el-table-bar-base 下，请移除原来的包，安装此包即可，功能不变。造成困扰，实在抱歉

**Comment by brightlight2017** [comment]
多谢及时更新，已可使用。

**Comment by brightlight2017** [comment]
readme部分也更新一下吧。

**Comment by JdesEva** [comment]
github上已经更新


在 2019-06-03 13:58:31，"suchenglin2017" <notifications@github.com> 写道：


readme部分也更新一下吧。
