### ISSUE TITLE
【bug】列表切换的时候横向滚动条fixed属性不生效

### ISSUE THREAD

**Issue by luxiangxiong** [JdesHZ/el-table-bar#10]
作者你好，我在用这个组件的时候遇到了一些问题。
我在一个页面里有6个按钮，每个按钮点击会切换一个列表（table是共用的，差别在表头）。
其中列表2**无任何内容**，其他列表都有内容。
1. 如果先将鼠标移到列表2，此时fixed会失效，此时切换到列表3456的话，鼠标放进列表里面fixed不会生效，无法固定。但从列表2切换到列表1，fixed是可以生效的。
2. 列表13456相互切换fixed是正常生效的，唯独切换到列表2之后就会出现上面⬆️的问题
3. 另外在页面初始化的时候，我测试了一下，只有在初始化列表是列表1的时候fixed会生效，初始化列表是其他列表的时候fixed都没有生效。

**Comment by JdesEva** [comment]
> 作者你好，我在用这个组件的时候遇到了一些问题。
> 我在一个页面里有6个按钮，每个按钮点击会切换一个列表（table是共用的，差别在表头）。
> 其中列表2**无任何内容**，其他列表都有内容。
> 
> 1. 如果先将鼠标移到列表2，此时fixed会失效，此时切换到列表3456的话，鼠标放进列表里面fixed不会生效，无法固定。但从列表2切换到列表1，fixed是可以生效的。
> 2. 列表13456相互切换fixed是正常生效的，唯独切换到列表2之后就会出现上面⬆️的问题
> 3. 另外在页面初始化的时候，我测试了一下，只有在初始化列表是列表1的时候fixed会生效，初始化列表是其他列表的时候fixed都没有生效。

已知悉，稍后定位

**Comment by JdesEva** [comment]
可以查看项目代码，本身fixed属性计算依据就是 el-table 的表头，默认表头固定。根据测试，如果仅仅更换表格内容，不更换表头，功能可用。建议修改实现方式。 @luxiangxiong

**Comment by luxiangxiong** [comment]
收到，辛苦了。

**Comment by luxiangxiong** [comment]
> 可以查看项目代码，本身fixed属性计算依据就是 el-table 的表头，默认表头固定。根据测试，如果仅仅更换表格内容，不更换表头，功能可用。建议修改实现方式。 @luxiangxiong

刚看了下好像跟表头无关，我从列表1切换到列表3456fixed是正常的，他们的表头是不一样的。如果我将列表4的内容清空，也是会出现上述的问题

**Comment by luxiangxiong** [comment]
对了，还想请问下有没有windows的css样式，用了一下发现是mac的滚动条样式。在windows上显示的滚动条有点偏细了

**Comment by JdesEva** [comment]
> 对了，还想请问下有没有windows的css样式，用了一下发现是mac的滚动条样式。在windows上显示的滚动条有点偏细了

这个用的是elementUI的不开放组件el-scrollbar实现的。我做的仅仅是对el-table滚动做了处理。UI层面我无能为力。

**Comment by luxiangxiong** [comment]
> > 对了，还想请问下有没有windows的css样式，用了一下发现是mac的滚动条样式。在windows上显示的滚动条有点偏细了
> 
> 这个用的是elementUI的不开放组件el-scrollbar实现的。我做的仅仅是对el-table滚动做了处理。UI层面我无能为力。

dalao我又发现了一个类似上面切换的bug，在一个列表里，因为数据过多，我底部加了一个分页导航。切换页码的时候鼠标移出再移进去fixed又不生效了

**Comment by luxiangxiong** [comment]
> > 对了，还想请问下有没有windows的css样式，用了一下发现是mac的滚动条样式。在windows上显示的滚动条有点偏细了
> 
> 这个用的是elementUI的不开放组件el-scrollbar实现的。我做的仅仅是对el-table滚动做了处理。UI层面我无能为力。

我看了一遍源码，大概发现了问题所在。翻页还有切换列表的时候，触发了updated，我在updated里面console.log（this.isbottom）发现是false的，然后resetstyle中fixed的开启又是根据this.isbottom来开启，所以fixed在上述情况失效了。

**Comment by JdesEva** [comment]
> > > 对了，还想请问下有没有windows的css样式，用了一下发现是mac的滚动条样式。在windows上显示的滚动条有点偏细了
> > 
> > 
> > 这个用的是elementUI的不开放组件el-scrollbar实现的。我做的仅仅是对el-table滚动做了处理。UI层面我无能为力。
> 
> 我看了一遍源码，大概发现了问题所在。翻页还有切换列表的时候，触发了updated，我在updated里面console.log（this.isbottom）发现是false的，然后resetstyle中fixed的开启又是根据this.isbottom来开启，所以fixed在上述情况失效了。

本地尝试使用分页器附带定时器模拟翻页请求事件。并没有复现出这个问题。demo可以参考examples中的示例。欢迎给出复现代码，便于定位问题~

**Comment by luxiangxiong** [comment]
> > > > 对了，还想请问下有没有windows的css样式，用了一下发现是mac的滚动条样式。在windows上显示的滚动条有点偏细了
> > > 
> > > 
> > > 这个用的是elementUI的不开放组件el-scrollbar实现的。我做的仅仅是对el-table滚动做了处理。UI层面我无能为力。
> > 
> > 
> > 我看了一遍源码，大概发现了问题所在。翻页还有切换列表的时候，触发了updated，我在updated里面console.log（this.isbottom）发现是false的，然后resetstyle中fixed的开启又是根据this.isbottom来开启，所以fixed在上述情况失效了。
> 
> 本地尝试使用分页器附带定时器模拟翻页请求事件。并没有复现出这个问题。demo可以参考examples中的示例。欢迎给出复现代码，便于定位问题~

代码与你的examples示例中的区别不大，差别在与 _initTableList ()中，我没有写this.vdata = []，而是直接赋值，试了一下，这样fixed在翻页后是没生效的。

**Comment by JdesEva** [comment]
> > > > > 对了，还想请问下有没有windows的css样式，用了一下发现是mac的滚动条样式。在windows上显示的滚动条有点偏细了
> > > > 
> > > > 
> > > > 这个用的是elementUI的不开放组件el-scrollbar实现的。我做的仅仅是对el-table滚动做了处理。UI层面我无能为力。
> > > 
> > > 
> > > 我看了一遍源码，大概发现了问题所在。翻页还有切换列表的时候，触发了updated，我在updated里面console.log（this.isbottom）发现是false的，然后resetstyle中fixed的开启又是根据this.isbottom来开启，所以fixed在上述情况失效了。
> > 
> > 
> > 本地尝试使用分页器附带定时器模拟翻页请求事件。并没有复现出这个问题。demo可以参考examples中的示例。欢迎给出复现代码，便于定位问题~
> 
> 代码与你的examples示例中的区别不大，差别在与 _initTableList ()中，我没有写this.vdata = []，而是直接赋值，试了一下，这样fixed在翻页后是没生效的。

尝试过了 直接赋值没有影响 依然可以使用。。。

**Comment by luxiangxiong** [comment]
> > > > > > 对了，还想请问下有没有windows的css样式，用了一下发现是mac的滚动条样式。在windows上显示的滚动条有点偏细了
> > > > > 
> > > > > 
> > > > > 这个用的是elementUI的不开放组件el-scrollbar实现的。我做的仅仅是对el-table滚动做了处理。UI层面我无能为力。
> > > > 
> > > > 
> > > > 我看了一遍源码，大概发现了问题所在。翻页还有切换列表的时候，触发了updated，我在updated里面console.log（this.isbottom）发现是false的，然后resetstyle中fixed的开启又是根据this.isbottom来开启，所以fixed在上述情况失效了。
> > > 
> > > 
> > > 本地尝试使用分页器附带定时器模拟翻页请求事件。并没有复现出这个问题。demo可以参考examples中的示例。欢迎给出复现代码，便于定位问题~
> > 
> > 
> > 代码与你的examples示例中的区别不大，差别在与 _initTableList ()中，我没有写this.vdata = []，而是直接赋值，试了一下，这样fixed在翻页后是没生效的。
> 
> 尝试过了 直接赋值没有影响 依然可以使用。。。

这就很奇怪了......难道是我的element-ui版本太低了？我司用的还是2.5.4的版本，我尝试下升级element-ui

**Comment by JdesEva** [comment]
> > > > > > > 对了，还想请问下有没有windows的css样式，用了一下发现是mac的滚动条样式。在windows上显示的滚动条有点偏细了
> > > > > > 
> > > > > > 
> > > > > > 这个用的是elementUI的不开放组件el-scrollbar实现的。我做的仅仅是对el-table滚动做了处理。UI层面我无能为力。
> > > > > 
> > > > > 
> > > > > 我看了一遍源码，大概发现了问题所在。翻页还有切换列表的时候，触发了updated，我在updated里面console.log（this.isbottom）发现是false的，然后resetstyle中fixed的开启又是根据this.isbottom来开启，所以fixed在上述情况失效了。
> > > > 
> > > > 
> > > > 本地尝试使用分页器附带定时器模拟翻页请求事件。并没有复现出这个问题。demo可以参考examples中的示例。欢迎给出复现代码，便于定位问题~
> > > 
> > > 
> > > 代码与你的examples示例中的区别不大，差别在与 _initTableList ()中，我没有写this.vdata = []，而是直接赋值，试了一下，这样fixed在翻页后是没生效的。
> > 
> > 
> > 尝试过了 直接赋值没有影响 依然可以使用。。。
> 
> 这就很奇怪了......难道是我的element-ui版本太低了？我司用的还是2.5.4的版本，我尝试下升级element-ui

看一下分页器是不是位于 组件内了？正确的使用方法应该是不能放在组件内部的
