### ISSUE TITLE
添加翻页器后 失效

### ISSUE THREAD

**Issue by caiguo168** [JdesHZ/el-table-bar#11]
你好，在使用插件中 由于使用了翻页器不能正常使用，el-table-bar :fixed="true"> el-table> </el-table>  el-pagination> </el-pagination> el-table-bar>，希望修正一下 谢谢！

**Comment by JdesEva** [comment]
> 你好，在使用插件中 由于使用了翻页器不能正常使用，el-table-bar :fixed="true"> el-table> el-pagination> el-table-bar>，希望修正一下 谢谢！

~能提供一下复现办法吗？可以贴部分代码方便复现。我本地尝试并没有复现这个问题

**Comment by caiguo168** [comment]
`<el-table-bar :fixed="true"> <el-table></el-table>  <el-pagination> </el-pagination> </el-table-bar>`, 这样 把el-pagination包在el-table-bar中，

**Comment by caiguo168** [comment]
> > 你好，在使用插件中 由于使用了翻页器不能正常使用，el-table-bar :fixed="true"> el-table> el-pagination> el-table-bar>，希望修正一下 谢谢！
> 
> ~能提供一下复现办法吗？可以贴部分代码方便复现。我本地尝试并没有复现这个问题

`<el-table-bar :fixed="true"> <el-table></el-table> <el-pagination> </el-pagination> </el-table-bar>` , 这样 把el-pagination包在el-table-bar中，

**Comment by JdesEva** [comment]
> > > 你好，在使用插件中 由于使用了翻页器不能正常使用，el-table-bar :fixed="true"> el-table> el-pagination> el-table-bar>，希望修正一下 谢谢！
> > 
> > 
> > ~能提供一下复现办法吗？可以贴部分代码方便复现。我本地尝试并没有复现这个问题
> 
> `<el-table-bar :fixed="true"> <el-table></el-table> <el-pagination> </el-pagination> </el-table-bar>` , 这样 把el-pagination包在el-table-bar中，

使用方法不对 应该是 `<el-table-bar :fixed="true"> <el-table></el-table>  </el-table-bar><el-pagination> </el-pagination>`

分页器不能包裹在 el-table-bar 组件内

**Comment by caiguo168** [comment]
> > > > 你好，在使用插件中 由于使用了翻页器不能正常使用，el-table-bar :fixed="true"> el-table> el-pagination> el-table-bar>，希望修正一下 谢谢！
> > > 
> > > 
> > > ~能提供一下复现办法吗？可以贴部分代码方便复现。我本地尝试并没有复现这个问题
> > 
> > 
> > `<el-table-bar :fixed="true"> <el-table></el-table> <el-pagination> </el-pagination> </el-table-bar>` , 这样 把el-pagination包在el-table-bar中，
> 
> 使用方法不对 应该是 `<el-table-bar :fixed="true"> <el-table></el-table> </el-table-bar><el-pagination> </el-pagination>`
> 
> 分页器不能包裹在 el-table-bar 组件内

主要是不包在里面， 鼠标移入翻页器的时候 滚动条隐藏了，再往下，移动到屏幕底部 滚动条才出现。多谢了，我在想想其他办法。
