### ISSUE TITLE
完全没效果

### ISSUE THREAD

**Issue by RichardRourc** [JdesHZ/el-table-bar#12]
![image](https://user-images.githubusercontent.com/46982566/96993806-61fcd200-155e-11eb-8408-c722908fc1ba.png)

**Comment by RichardRourc** [comment]
<el-table-bar fixed native>
        <el-table
          border
          :data="tableData"
          v-loading="loading"
          element-loading-text="拼命加载中"
          element-loading-spinner="el-icon-loading"
          style="width: 100%;"
          :row-class-name="$tableRowClassName"
        >

-------main.js
import ElTableBar from "el-table-bar-base"
import "el-table-bar-base/lib/ElTableBar.css"

Vue.use(ElTableBar)

**Comment by JdesEva** [comment]
需要引入element-ui的el-scrollbar组件 没有做内置引入。手动引入即可

**Comment by RichardRourc** [comment]
> el-scrollbar

我这里后台是引入了整个element-ui的诶，尝试按需引入了el-scrollbar也还是无效
![image](https://user-images.githubusercontent.com/46982566/97126910-225b0380-1773-11eb-8a96-c48458cf1db1.png)

**Comment by JdesEva** [comment]
....去掉native属性 native代表原生滚动条......

**Comment by RichardRourc** [comment]
> ....去掉native属性 native代表原生滚动条......

额。我表格操作列设置了fixed不是要设置这个属性吗。而且就算去掉这个native也还是没变化诶。害

**Comment by JdesEva** [comment]
![image](https://user-images.githubusercontent.com/37232561/97517883-0c4a7e80-19d1-11eb-8f43-7c5b1b4aecf2.png)
![image](https://user-images.githubusercontent.com/37232561/97517891-12405f80-19d1-11eb-9e7a-76bdbe4e0db2.png)


表格宽度需要大于一定程度，保证容器宽度不够，导致滚动条出现，此时插件会自动计算，显示出滚动条。
这是插件正常显示的充分必要条件，如果表格宽度不够大 是不会有任何现象的
