### ISSUE TITLE
列表加载完成之后，需要出发一次点击事件才生效

### ISSUE THREAD

**Issue by frogprincehe** [JdesHZ/el-table-bar#13]
你好
   我的问题很奇怪，使用fixed之后，需要点击一次列表的cell-click 之后滚动条才生效。
cell-click触发的是一个el-dialog，这个el-dialog写在table外。看了下解析的HTML，我点击之后才加载了横向滚动的CSS。
![image](https://user-images.githubusercontent.com/14307547/99666717-4e358480-2aa6-11eb-9278-4db12b6aa3b7.png)

点击之前的HTML
![image](https://user-images.githubusercontent.com/14307547/99666817-76bd7e80-2aa6-11eb-818f-3292e80e17c2.png)

点击之后的
![image](https://user-images.githubusercontent.com/14307547/99667130-e59ad780-2aa6-11eb-93b5-0fb339eca6e0.png)

**Comment by JdesEva** [comment]
我在本地没有复现成功 可以查看我最新推送的代码中的examples中的例子
