### ISSUE TITLE
关于fixed和el-table-columns 的fixed问题

### ISSUE THREAD

**Issue by Lion0707** [JdesHZ/el-table-bar#14]
请教您一个问题，当我使用了您的el-table-bar的时候，我还想要将前两个column固定，我的设置如图所示，
![code](https://user-images.githubusercontent.com/24955482/102465401-8ec5f500-4088-11eb-924d-17a1a33b48fa.png)
但是却发现横向的scrollbar失效了，是我的设置有问题嘛？  

![view](https://user-images.githubusercontent.com/24955482/102465515-b2893b00-4088-11eb-8fa9-695953b96d71.jpg)
PS：  图好像挂了？

请不吝指教，谢谢额

**Comment by Lion0707** [comment]
``` vue
    <el-table-bar fixed native=true>
    <el-table :data="cmpDiff_Detail[1]"
        v-loading="loadDetails"
        element-loading-text="解析数据ing..."
        :row-style="{height:0+'px'}"
        :cell-style="{padding:0+'px'}"
        max-height="500px"
        border
        fit
        style="width: 100%"
        highlight-current-row
        :header-cell-style="{background:'#eef1f6',color:'#606266'}"
    >
    <el-table-column fixed="left"  label="观测"  prop="obs" width="50px">
    </el-table-column> 
    <el-table-column fixed="left"   label="类型"  width="60px">
      <template slot-scope="scope">
        {{scope.row._set_ord == 1 ? "BASE" : "CMP"}}
      </template>
    </el-table-column> 
     </el-table>
     </el-table-bar>
```

**Comment by JdesEva** [comment]
> ```
>     <el-table-bar fixed native=true>
>     <el-table :data="cmpDiff_Detail[1]"
>         v-loading="loadDetails"
>         element-loading-text="解析数据ing..."
>         :row-style="{height:0+'px'}"
>         :cell-style="{padding:0+'px'}"
>         max-height="500px"
>         border
>         fit
>         style="width: 100%"
>         highlight-current-row
>         :header-cell-style="{background:'#eef1f6',color:'#606266'}"
>     >
>     <el-table-column fixed="left"  label="观测"  prop="obs" width="50px">
>     </el-table-column> 
>     <el-table-column fixed="left"   label="类型"  width="60px">
>       <template slot-scope="scope">
>         {{scope.row._set_ord == 1 ? "BASE" : "CMP"}}
>       </template>
>     </el-table-column> 
>      </el-table>
>      </el-table-bar>
> ```

横向滚动和el-table的fixed模式冲突，无法同时使用。这是因为el-scrollbar的滚动原理导致的，代码层面无法给出解决方案。~同时，你的这个native属性写的有点小问题~
![image](https://user-images.githubusercontent.com/37232561/102569313-35110980-4120-11eb-8f1f-be8a6fb82740.png)
native是用来还原滚动条的~

**Comment by Lion0707** [comment]
@JdesEva  嗯嗯  好的  谢谢你的解答
