### ISSUE TITLE
el原生el-table-column的fixed属性失效，滑动了整个table

### ISSUE THREAD

**Issue by binbinlau** [JdesHZ/el-table-bar#15]
el原生el-table-column的fixed属性失效，滑动了整个table，是否能实现仅对没有加fixed的列进行滚动

**Comment by JdesEva** [comment]
> el原生el-table-column的fixed属性失效，滑动了整个table，是否能实现仅对没有加fixed的列进行滚动

fixed不支持 el-table-column的fixed模式，这是由于 el-scrollbar 组件的滚动原理导致的 也可以说是  el-table-column的fixed原理导致的，无法实现此功能。
