### ISSUE TITLE
表格固定列时不生效的问题

### ISSUE THREAD

**Issue by brightlight2017** [JdesHZ/el-table-bar#3]
你好，我这边需要固定最后一列，添加了element ui的fixed="right"属性，但没有达到目的，请问你这边看看能否兼容一下呢？

**Comment by JdesEva** [comment]
确认有这个问题，待修复

**Comment by JdesEva** [comment]
> 你好，我这边需要固定最后一列，添加了element ui的fixed="right"属性，但没有达到目的，请问你这边看看能否兼容一下呢？

目前没找到解决办法....建议不要一起使用两者。可以新增一个属性，检测fixed属性存在还原为原生滚动条

**Comment by brightlight2017** [comment]
这也是个思路。
如果使用了固定列，固定表头等功能，就使用原生的。

**Comment by JdesEva** [comment]
> 这也是个思路。
> 如果使用了固定列，固定表头等功能，就使用原生的。

新加了个native属性，默认false，如果需要固定列设置为 true 就会还原成原生。已更新2.0.9。感谢指正问题。

**Comment by JdesEva** [comment]
> 这也是个思路。
> 如果使用了固定列，固定表头等功能，就使用原生的。

其实感觉这个功能有点鸡肋，除非设置的fixed是动态的，会根据props改变。
